on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - run: deno tasks unit-test
