on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Unit Test
        run: deno task unit-test
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.PROJECT_KEY }}
          entrypoint: "./src/main.ts"
      - run: sed -i s/PROJECT_KEY/${{ secrets.PROJECT_KEY }}/g api_testing/newman.json
      - uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json
          environment: postman_environment.json
